name = "muddy-tooth-e4be"
main = "src/index.js"
compatibility_date = "2026-09-20"

[[d1_databases]]
binding = "DB"
database_name = "sss"
database_id = "57064739-5e86-4d4f-b9d7-d223a5b38642"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sss"

[vars]
FRONTEND_ORIGIN = "https://dangero11.netlify.app"
BREVO_SENDER_EMAIL = "growthmedia70@gmail.com"
BREVO_SENDER_NAME = "sphere"

[[durable_objects.bindings]]
name = "SPACE_ROOM"
class_name = "SpaceRoom"
