import {
  clearSessionCookie,
  createPersistedSession,
  createSessionCookie,
  hashPassword,
  resolveSession,
  revokeSession,
  validateCredentials,
  verifyPassword,
} from "./auth.js";
import { createPost, getPost, listFeed } from "./posts.js";
import { createReply, listReplies } from "./replies.js";
import { setPostAction, setRelationship, sharePostWithFollowers, listSavedPosts } from "./social.js";
import { search } from "./search.js";
import { createConversation, listConversations, listMessages, markConversationRead, sendMessage } from "./messages.js";
import { listNotifications, markAllNotificationsRead, markNotificationRead } from "./notifications.js";
import { getMyProfile, getProfile, listProfilePosts, updateMyProfile } from "./profile.js";
import { deleteMedia, getMedia, uploadMedia } from "./media.js";
import { getMySettings, updateMySettings } from "./settings.js";
import { browseMusic, searchMusic } from "./music.js";
import { requestPasswordReset, confirmPasswordReset } from "./passwordReset.js";

const JSON_HEADERS = { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" };
const MAX_BODY_BYTES = 16 * 1024;

function corsHeaders(request, env) { const origin = request.headers.get("Origin"); const headers = new Headers(JSON_HEADERS); if (origin && env?.FRONTEND_ORIGIN && origin === env.FRONTEND_ORIGIN) { headers.set("access-control-allow-origin", origin); headers.set("access-control-allow-credentials", "true"); headers.set("vary", "Origin"); } return headers; }
function json(data, status = 200, request, env, extraHeaders = {}) { const headers = corsHeaders(request, env); Object.entries(extraHeaders).forEach(([name, value]) => headers.set(name, value)); return new Response(JSON.stringify(data), { status, headers }); }
function errorResponse(code, status, message, request, env, details) { return json({ error: { code, status, message, ...(details === undefined ? {} : { details }) } }, status, request, env); }
function methodNotAllowed(request, env) { return errorResponse("METHOD_NOT_ALLOWED", 405, "Method not allowed.", request, env); }
function mutationOriginAllowed(request, env) { return !env?.FRONTEND_ORIGIN || request.headers.get("Origin") === env.FRONTEND_ORIGIN; }
function originRejected(request, env) { return errorResponse("FORBIDDEN_ORIGIN", 403, "Request origin is not allowed.", request, env); }
async function readJson(request) { const contentLength = Number(request.headers.get("Content-Length")); if (Number.isFinite(contentLength) && contentLength > MAX_BODY_BYTES) return { error: "PAYLOAD_TOO_LARGE" }; const text = await request.text(); if (new TextEncoder().encode(text).byteLength > MAX_BODY_BYTES) return { error: "PAYLOAD_TOO_LARGE" }; if (!text.trim()) return { value: {} }; try { return { value: JSON.parse(text) }; } catch { return { error: "INVALID_JSON" }; } }
function userPayload(user) { return { id: user.id, username: user.username, displayName: user.display_name }; }
async function signUp(request, env) { try { if (!env?.DB) return errorResponse("SERVICE_UNAVAILABLE", 503, "Authentication service is not configured.", request, env); const body = await readJson(request); if (body.error === "PAYLOAD_TOO_LARGE") return errorResponse("PAYLOAD_TOO_LARGE", 413, "Request body is too large.", request, env); if (body.error) return errorResponse("INVALID_JSON", 400, "Request body must be valid JSON.", request, env); const credentials = validateCredentials(body.value); if (!credentials.valid) return errorResponse("VALIDATION_ERROR", 400, "Please correct the highlighted fields.", request, env, credentials.errors); const displayName = String(body.value.displayName || credentials.username).trim().slice(0, 60); if (!displayName) return errorResponse("VALIDATION_ERROR", 400, "Display name is required.", request, env); const existing = await env.DB.prepare("SELECT id FROM users WHERE username = ?1 OR email = ?2 LIMIT 1").bind(credentials.username, credentials.email).first(); if (existing) return errorResponse("ACCOUNT_EXISTS", 409, "An account with those details already exists.", request, env); const userId = globalThis.crypto.randomUUID(); await env.DB.prepare("INSERT INTO users (id, username, display_name, email, password_hash) VALUES (?1, ?2, ?3, ?4, ?5)").bind(userId, credentials.username, displayName, credentials.email, await hashPassword(body.value.password)).run(); const token = await createPersistedSession(userId, env); return json({ authenticated: true, user: { id: userId, username: credentials.username, displayName } }, 201, request, env, { "set-cookie": createSessionCookie(token) }); }
catch (error) { console.error("AUTH_SIGN_UP_EXCEPTION", error); const details = env?.DEBUG_AUTH_ERRORS === "true" ? String(error?.message || error?.name || "unknown") : undefined; return errorResponse("AUTH_INTERNAL_ERROR", 500, "Authentication could not be completed.", request, env, details); } }
async function signIn(request, env) { if (!env?.DB) return errorResponse("SERVICE_UNAVAILABLE", 503, "Authentication service is not configured.", request, env); const body = await readJson(request); if (body.error === "PAYLOAD_TOO_LARGE") return errorResponse("PAYLOAD_TOO_LARGE", 413, "Request body is too large.", request, env); if (body.error) return errorResponse("INVALID_JSON", 400, "Request body must be valid JSON.", request, env); const identifier = String(body.value.identifier || body.value.username || body.value.email || "").trim().toLowerCase(); const password = body.value.password; if (!identifier || typeof password !== "string" || password.length > 128) return errorResponse("INVALID_CREDENTIALS", 401, "Invalid credentials.", request, env); const user = await env.DB.prepare("SELECT id, username, display_name, password_hash FROM users WHERE (username = ?1 OR email = ?1) AND deleted_at IS NULL LIMIT 1").bind(identifier).first(); if (!user || !(await verifyPassword(password, user.password_hash))) return errorResponse("INVALID_CREDENTIALS", 401, "Invalid credentials.", request, env); const token = await createPersistedSession(user.id, env); return json({ authenticated: true, user: userPayload(user) }, 200, request, env, { "set-cookie": createSessionCookie(token) }); }

export default { async fetch(request, env) {
  const url = new URL(request.url);
  if (request.method === "OPTIONS") { const headers = corsHeaders(request, env); headers.set("access-control-allow-methods", "GET,POST,PUT,PATCH,DELETE,OPTIONS"); headers.set("access-control-allow-headers", "content-type, authorization, x-request-id"); return new Response(null, { status: 204, headers }); }
  if (url.pathname === "/health" || url.pathname === "/api/health") { if (request.method !== "GET") return methodNotAllowed(request, env); return json({ ok: true, service: "sss-api", version: "0.1.0" }, 200, request, env); }
  if (url.pathname === "/api/media/upload") {
    if (request.method !== "POST") return methodNotAllowed(request, env);
    if (!mutationOriginAllowed(request, env)) return originRejected(request, env);
    const result = await uploadMedia(request, env);
    if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details);
    return json(result.response, 201, request, env);
  }
  const mediaMatch = url.pathname.match(/^\/api\/media\/([^/]+)$/);
  if (mediaMatch) {
    const mediaId = decodeURIComponent(mediaMatch[1]);
    if (request.method === "GET") { const result = await getMedia(request, env, mediaId); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return result.response; }
    if (request.method === "DELETE") { if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await deleteMedia(request, env, mediaId); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
    return methodNotAllowed(request, env);
  }
  const postDetailMatch = url.pathname.match(/^\/api\/posts\/([^/]+)$/);
  if (postDetailMatch) { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await getPost(request, env, decodeURIComponent(postDetailMatch[1])); if (result.error) return errorResponse(result.error.code,result.error.status,result.error.message,request,env,result.error.details); return json(result.response,200,request,env); }\n  if (url.pathname === "/api/posts") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await createPost(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 201, request, env); }
  if (url.pathname === "/api/feed") { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await listFeed(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  const repliesMatch = url.pathname.match(/^\/api\/posts\/([^/]+)\/replies$/);
  if (repliesMatch) {
    const postId = decodeURIComponent(repliesMatch[1]);
    if (request.method === "GET") { const result = await listReplies(request, env, postId); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
    if (request.method === "POST") { if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await createReply(request, env, postId); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 201, request, env); }
    return methodNotAllowed(request, env);
  }
  if (url.pathname === "/api/social/relationships") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await setRelationship(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  const postShare = url.pathname.match(/^\/api\/social\/posts\/([^/]+)\/share$/);
  if (postShare) { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await sharePostWithFollowers(request, env, decodeURIComponent(postShare[1])); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/bookmarks") { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await listSavedPosts(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/search") { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await search(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/music/search") { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await searchMusic(request); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/music/browse") { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await browseMusic(request); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  const postAction = url.pathname.match(/^\/api\/social\/posts\/([^/]+)\/(like|repost|bookmark)$/);
  if (postAction) { if (!['POST','DELETE'].includes(request.method)) return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await setPostAction(request, env, decodeURIComponent(postAction[1]), postAction[2]); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/messages/conversations") { if (request.method === "GET") { const result = await listConversations(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); } if (request.method === "POST") { if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await createConversation(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 201, request, env); } return methodNotAllowed(request, env); }
  const conversationMatch = url.pathname.match(/^\/api\/messages\/conversations\/([^/]+)(?:\/read)?$/);
  if (conversationMatch) { const conversationId = decodeURIComponent(conversationMatch[1]); if (url.pathname.endsWith("/read")) { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await markConversationRead(request, env, conversationId); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); } if (request.method !== "GET") return methodNotAllowed(request, env); const result = await listMessages(request, env, conversationId); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/messages") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await sendMessage(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 201, request, env); }
  if (url.pathname === "/api/notifications") { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await listNotifications(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/notifications/read") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await markNotificationRead(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/notifications/read-all") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await markAllNotificationsRead(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/settings/me") { if (request.method === "GET") { const result = await getMySettings(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); } if (request.method === "PATCH") { if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await updateMySettings(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); } return methodNotAllowed(request, env); }
  if (url.pathname === "/api/profile/me") { if (request.method === "GET") { const result = await getMyProfile(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); } if (request.method === "PATCH") { if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await updateMyProfile(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); } return methodNotAllowed(request, env); }
  const profilePostsMatch = url.pathname.match(/^\/api\/profile\/([^/]+)\/posts$/);
  if (profilePostsMatch) { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await listProfilePosts(request, env, decodeURIComponent(profilePostsMatch[1])); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  const profileMatch = url.pathname.match(/^\/api\/profile\/([^/]+)$/);
  if (profileMatch) { if (request.method !== "GET") return methodNotAllowed(request, env); const result = await getProfile(request, env, decodeURIComponent(profileMatch[1])); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env, result.error.details); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/auth/session") { if (request.method !== "GET") return methodNotAllowed(request, env); const session = await resolveSession(request, env); if (!session) return json({ authenticated: false, user: null }, 200, request, env); return json({ authenticated: true, user: userPayload(session) }, 200, request, env); }
  if (url.pathname === "/api/auth/sign-up") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); return signUp(request, env); }
  if (url.pathname === "/api/auth/sign-in") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); return signIn(request, env); }
  if (url.pathname === "/api/auth/password-reset/request") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await requestPasswordReset(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/auth/password-reset/confirm") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); const result = await confirmPasswordReset(request, env); if (result.error) return errorResponse(result.error.code, result.error.status, result.error.message, request, env); return json(result.response, 200, request, env); }
  if (url.pathname === "/api/auth/sign-out") { if (request.method !== "POST") return methodNotAllowed(request, env); if (!mutationOriginAllowed(request, env)) return originRejected(request, env); await revokeSession(request, env); return json({ ok: true }, 200, request, env, { "set-cookie": clearSessionCookie() }); }
  return errorResponse("NOT_FOUND", 404, "Route not found.", request, env);
} };
