import React from "react";
import { ArrowLeft, Bookmark, Link2, MessageCircle, Repeat2, Send, Share2, Users } from "lucide-react";
export default function EntityRoute({ path, posts, onBack, onOpen, onSave }) {
  const parts = path.split("/").filter(Boolean);
  const type = parts[0];
  const id = parts[1];
  const post = posts.find((p) => String(p.id) === String(id)) || posts[0];
  if (type === "post" || type === "share") return <div className="detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={17}/>Back</button><article className="detail-post"><div className="avatar">{(post.a || "S")[0]}</div><div><strong>{post.a}</strong><span className="muted"> @{String(post.h || "@user").replace("@","")}</span><p>{post.x}</p>{post.media && <div className="post-media"><span>Visual expression</span></div>}{post.music && <div className="audio-card">Original audio · Late Night Notes</div>}<div className="detail-actions"><button><MessageCircle/>Reply</button><button><Repeat2/>Repost</button><button><Bookmark onClick={() => onSave?.(post.id)}/>Save</button><button><Send/>Share</button></div></div></article><section className="thread"><h3>Replies</h3><div className="empty"><p>Replies to this post will appear here.</p></div></section></div>;
  if (type === "user") return <div className="detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={17}/>Back</button><div className="entity-hero"><div className="avatar entity-avatar">M</div><h2>{id ? id[0].toUpperCase() + id.slice(1) : "User"}</h2><span>@{id || "user"}</span><p>Creator on S. Follow the conversation, posts and ideas from this profile.</p><div className="entity-stats"><b>1.8K <small>Followers</small></b><b>142 <small>Following</small></b></div><button className="primary">Follow</button></div></div>;
  if (type === "topic") return <div className="detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={17}/>Back</button><div className="entity-hero topic-hero"><span className="topic-icon">#</span><h2>{decodeURIComponent(id || "community")}</h2><p>Posts and conversations around this topic on S.</p><div className="entity-stats"><b>8.1K <small>Posts</small></b><b>24K <small>People</small></b></div></div>{posts.slice(0,5).map((p) => <div className="topic-post" key={p.id}><b>{p.a}</b><span className="muted"> {p.t}</span><p>{p.x}</p></div>)}</div>;
  if (type === "followers" || type === "following") return <div className="detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={17}/>Back</button><div className="heading"><small>PROFILE NETWORK</small><h2>{type === "followers" ? "Followers" : "Following"}</h2></div>{["Maya Okafor","Daniel Cole","Nia James","S Team"].map((name) => <div className="network-row" key={name}><div className="avatar avatar--small">{name[0]}</div><div><b>{name}</b><span>@{name.split(" ")[0].toLowerCase()}</span></div><button className="outline">Following</button></div>)}</div>;
  return <div className="detail-page"><div className="empty"><Users/><h3>S surface</h3><p>This destination is part of the frontend route map and is ready for its backend-backed data contract.</p></div></div>;
}
